name: Deploy to staging

on:
  pull_request:
      types: [labeled]

      #############################
      env:
        IMAGE_REGISTRY_URL: ghcr.io
          ###############################################
            ### Replace <username> with GitHub username ###
              ###############################################
                DOCKER_IMAGE_NAME: <username>-azure-ttt
                  AZURE_WEBAPP_NAME: <username>-ttt-app
                    ##################
